theme: jekyll-theme-time-machine

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - <the name of your second page>.md

title: <your webpage title>
description: <description of your webpage> 
